modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/refinedmods/refinedstorage-mekanism-integration"
license = "MIT"
[[mods]]
modId = "refinedstorage_mekanism_integration"
version = "${version}"
displayName = "Refined Storage - Mekanism Integration"
displayURL = "https://refinedmods.com/refined-storage"
authors = "Refined Mods"
description = '''
Mekanism integration for Refined Storage.
'''
[[dependencies.refinedstorage_mekanism_integration]]
modId = "refinedstorage"
type = "required"
versionRange = "2.0.0-milestone.4.12"
side = "BOTH"
[[dependencies.refinedstorage_mekanism_integration]]
modId = "mekanism"
type = "required"
versionRange = "[10.6,11-)"
side = "BOTH"